### ISSUE TITLE
PDAL installation error

### ISSUE THREAD

**Issue by niranjanreddy891** [mathieu1/pcl-stack#1]
Can anyone please specify the command to install PDAL using conda. I followed this tutorial to install PDAL. But it didnt worked. Thanks in advance

**Comment by mathieu1** [comment]
I expanded the [Readme](https://github.com/mathieu1/pcl-stack/blob/master/README.md) for basic installation steps (only ready for testing on macos or linux-64, with python 3.5 or 3.6)

Does that work for you?

**Comment by niranjanreddy891** [comment]
No, I am using win-7 64 bit with python 2.7 installed in it

**Comment by mathieu1** [comment]
Creating a package for python 2.7 should not be a problem, but Windows support is going to require significant work. I opened issue #2 to track the status of windows support, thanks for the report.
